### PR TITLE
Update terraform.tf

### PR DESCRIPTION
**Pull request by JFolberth**
Update min versions as called out https://github.com/Azure/terraform-azurerm-avm-res-managedidentity-userassignedidentity/pull/1#pullrequestreview-1916775159

### CODE REVIEW

**Comment by segraef** [comment]
Was this agreed with @matt-FFFFFF since your change removes the major version constraint.

**Comment by matt-FFFFFF** [comment]
This is fine, it's just another way of writing the same thing.

**Comment by lonegunmanb** [comment]
I don't think we need this pr for this template. I understand that @JFolberth want this change because the change he'd like to introduce in https://github.com/Azure/terraform-azurerm-avm-res-managedidentity-userassignedidentity/pull/1#pullrequestreview-1916775159 require this min versions restriction, but they're not required by all AVM repos. Each AVM repo could keep it's own provider versions restriction, but I think it's better to keep a loose restriction here in the template repo, otherwise enforcing a high version requirement could block our users from using some AVM modules. WDYT @JFolberth @matt-FFFFFF ?

**Comment by JFolberth** [comment]
I have no preference either way. Was just closing the loop on feedback from the module I was working on if it was something that should be addressed back to the template level.

**Review by lonegunmanb — APPROVED** [review]

**Pull request merged**
