### PR TITLE
fix: Update e2e test env `ARM_CLIENT_ID`

### PR DESCRIPTION
**Pull request by lonegunmanb**

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
@lonegunmanb I will test this in my module repo first, then merge

**Comment by matt-FFFFFF** [comment]
@lonegunmanb do we need this any more?

**Comment by segraef** [comment]
> @lonegunmanb do we need this any more?

@lonegunmanb your turn.

**Comment by matt-FFFFFF** [comment]
No longer needed

**Pull request closed without merging**
